pipeline {
    agent {
        docker {
            image 'qaninja/ruby-web-agent'
            args '--network rocklov-network'
        }
    }
    stages {
        stage('Prep'){
            steps {
                sh 'cd Web && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd Web && rake local_seeds'
                
            }
        }
        stage('UAT'){
            steps {
                echo 'Aguardando teste de aceitação.'
                input message: 'Podemos ir para produção?'
            }
        }
        stage('Prod') {
            steps {
                echo 'WebApp pronta'
            }
        }
    }
    post {
        always {
            echo 'ToDo'
        }
    }
}